// Code generated by Slice Machine. DO NOT EDIT.
import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type AccueilDocumentDataSlicesSlice = never

/**
 * Content for Accueil documents
 */
interface AccueilDocumentData {
  /**
   * Photo_Front field in *Accueil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.photo_front
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo_front: prismic.ImageField<never>

  /**
   * Photo_Back field in *Accueil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.photo_back
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo_back: prismic.ImageField<never>

  /**
   * Titre field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField

  /**
   * Text field in *Accueil*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField

  /**
   * Body field in *Accueil*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField

  /**
   * citation field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.citation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  citation: prismic.KeyTextField

  /**
   * Slice Zone field in *Accueil*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AccueilDocumentDataSlicesSlice>

  /**
   * Fin field in *Accueil*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.fin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  fin: prismic.RichTextField /**
   * Meta Description field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: accueil.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Accueil*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accueil.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Accueil*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: accueil.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Accueil document from Prismic
 *
 * - **API ID**: `accueil`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AccueilDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AccueilDocumentData>, 'accueil', Lang>

/**
 * Content for Amis_dans_Contact documents
 */
interface AmisDansContactDocumentData {
  /**
   * rank field in *Amis_dans_Contact*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: amis_dans_contact.rank
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rank: prismic.NumberField

  /**
   * Nom field in *Amis_dans_Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: amis_dans_contact.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Image field in *Amis_dans_Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: amis_dans_contact.img
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img: prismic.ImageField<never>

  /**
   * Réseau social field in *Amis_dans_Contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: amis_dans_contact.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField
}

/**
 * Amis_dans_Contact document from Prismic
 *
 * - **API ID**: `amis_dans_contact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AmisDansContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AmisDansContactDocumentData>,
    'amis_dans_contact',
    Lang
  >

type ContactDocumentDataSlicesSlice = never

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Phrase field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.phrase
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phrase: prismic.RichTextField

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    'contact',
    Lang
  >

/**
 * Content for Gyroroue documents
 */
interface GyroroueDocumentData {
  /**
   * Modèle field in *Gyroroue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.modele
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  modele: prismic.KeyTextField

  /**
   * Photo field in *Gyroroue*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>

  /**
   * Constructeur field in *Gyroroue*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.constructeur
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  constructeur: prismic.SelectField<
    'BEGODE' | 'EXTREME BULL' | 'INMOTION' | 'KINGSONG' | 'LEAPERKIM VETERAN'
  >

  /**
   * Date field in *Gyroroue*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField

  /**
   * Points field in *Gyroroue*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.points
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  points: prismic.NumberField

  /**
   * Equipement field in *Gyroroue*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.equipement
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  equipement: prismic.NumberField

  /**
   * Praticité field in *Gyroroue*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.praticite
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  praticite: prismic.NumberField

  /**
   * En ville field in *Gyroroue*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.en_ville
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  en_ville: prismic.NumberField

  /**
   * Sur route field in *Gyroroue*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.sur_route
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  sur_route: prismic.NumberField

  /**
   * Profil field in *Gyroroue*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.profil
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  profil: prismic.SelectField<'Polyvalente' | 'Routière' | 'Urbaine'>

  /**
   * Suspension field in *Gyroroue*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: gyroroue.suspension
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  suspension: prismic.BooleanField

  /**
   * Note field in *Gyroroue*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.note
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  note: prismic.NumberField

  /**
   * Commentaire field in *Gyroroue*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.commentaire
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  commentaire: prismic.KeyTextField

  /**
   * Lien vidéo Youtube field in *Gyroroue*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gyroroue.lien_video_youtube
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lien_video_youtube: prismic.LinkField
}

/**
 * Gyroroue document from Prismic
 *
 * - **API ID**: `gyroroue`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GyroroueDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GyroroueDocumentData>,
    'gyroroue',
    Lang
  >

/**
 * Content for Promo documents
 */
interface PromoDocumentData {
  /**
   * rank field in *Promo*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: promo.rank
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  rank: prismic.NumberField

  /**
   * name field in *Promo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promo.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * logo field in *Promo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promo.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>

  /**
   * logo_mode_sombre field in *Promo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promo.logo_mode_sombre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_mode_sombre: prismic.ImageField<never>

  /**
   * website field in *Promo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promo.website
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website: prismic.KeyTextField

  /**
   * description field in *Promo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promo.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField

  /**
   * code field in *Promo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promo.code
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  code: prismic.KeyTextField

  /**
   * montant field in *Promo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promo.montant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  montant: prismic.KeyTextField
}

/**
 * Promo document from Prismic
 *
 * - **API ID**: `promo`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PromoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PromoDocumentData>, 'promo', Lang>

export type AllDocumentTypes =
  | AccueilDocument
  | AmisDansContactDocument
  | ContactDocument
  | GyroroueDocument
  | PromoDocument

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AccueilDocument,
      AccueilDocumentData,
      AccueilDocumentDataSlicesSlice,
      AmisDansContactDocument,
      AmisDansContactDocumentData,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      GyroroueDocument,
      GyroroueDocumentData,
      PromoDocument,
      PromoDocumentData,
      AllDocumentTypes,
    }
  }
}
